import { useUI } from './UiContext';
import { useEffect, useRef, useState } from 'react';
import { aiClient, aiState } from '../ai/client';
import type { DraftResult, ExplainResult } from '../ai/schemas';
import { formatDay, type ScheduledPlan } from '../model/plan';
import BankableForm from './BankableForm';
import type { DispatchPlan } from './types';
export default function NodeDrawer({ id, scheduled, dispatch, onClose, onSelect, onAiMode, autoExplain, passive }: { id: string; scheduled: ScheduledPlan; dispatch: DispatchPlan; onClose: () => void; onSelect: (id: string) => void; onAiMode: (mode: 'live' | 'mock') => void; autoExplain: boolean; passive: boolean }) {
  const { t } = useUI();
  const dialog = useRef<HTMLDialogElement>(null), version = useRef(0);
  const node = scheduled.nodes[id], s = scheduled.schedule[id];
  const [explanation, setExplanation] = useState<ExplainResult | null>(null), [draft, setDraft] = useState<DraftResult | null>(null), [busy, setBusy] = useState(''), [error, setError] = useState(''), [copied, setCopied] = useState('');
  useEffect(() => { const el = dialog.current, previous = document.activeElement as HTMLElement | null; if (passive) el?.show(); else el?.showModal(); const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { version.current++; el?.close(); document.body.style.overflow = overflow; previous?.focus({ preventScroll: true }); }; }, []);
  async function run(kind: 'explain' | 'draft') {
    const requestVersion = version.current; setBusy(kind); setError('');
    try {
      if (kind === 'explain') { const result = await aiClient.explain({ nodeId: id, label: node.label, owner: node.owner, startDay: s.start, finishDay: s.finish, expectedDays: s.expectedDays, onCriticalPath: s.onCriticalPath, unlocks: s.unlocks, companyName: scheduled.company.name, zone: scheduled.company.zone, source: node.source }); if (requestVersion === version.current) setExplanation(result); }
      else { const person = scheduled.people.find(p => p.id === node.personId); const result = await aiClient.draft({ template: id === 'bank_account' ? 'bank_cover_letter' : 'employer_rent_guarantee', tone: 'formal', context: { companyName: scheduled.company.name, activity: scheduled.company.activity, zone: scheduled.company.zone, headcount: String(scheduled.company.headcount), inflows: `AED ${scheduled.company.ownership.expectedMonthlyInflowsAED}`, ...(person ? { employeeName: person.name, role: person.role, salary: String(person.basicSalaryAED) } : {}) } }); if (requestVersion === version.current) setDraft(result); }
      onAiMode(aiState.lastMode);
    } catch { if (requestVersion === version.current) setError('Could not prepare the response. Try again.'); }
    finally { if (requestVersion === version.current) setBusy(''); }
  }
  useEffect(() => { if (autoExplain) void run('explain'); }, [autoExplain]);
  async function copy(text: string, language: string) { try { await navigator.clipboard.writeText(text); setCopied(language); } catch { setError('Clipboard unavailable. Select the letter text to copy it.'); } }
  return <dialog ref={dialog} className="node-drawer" aria-labelledby="node-title" onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === dialog.current) onClose(); }}><div className="drawer-inner"><div className="drawer-head"><span className={`owner owner-${node.owner}`}>{node.owner}</span><button className="ls-btn secondary" onClick={onClose} aria-label="Close step details">{t('Close ×')}</button></div><h2 id="node-title">{t(node.label)}</h2><p className="mono-text">median {node.medianDays} d · p80 {node.p80Days} d · expected {s.expectedDays.toFixed(1)} d</p><p>{formatDay(scheduled.company.startDate, s.start)} → {formatDay(scheduled.company.startDate, s.finish)}</p><p className={s.onCriticalPath ? 'crit-text' : 'muted'}>{s.onCriticalPath ? 'On your critical path' : 'Running in parallel'} · unlocks {s.unlocks} steps</p><h3>{t('Depends on')}</h3>{node.dependsOn.length ? <div className="dependency-list">{node.dependsOn.map(dep => <button key={dep} onClick={() => onSelect(dep)}>{scheduled.nodes[dep]?.label ?? dep} →</button>)}</div> : <p>No dependencies. {s.start === 0 && 'Start today.'}</p>}<h3>{t('Source')}</h3><p className="source-copy">{node.source}</p><div className="drawer-actions"><button className="ls-btn primary" disabled={!!busy} onClick={() => void run('explain')}>{busy === 'explain' ? 'Preparing explanation…' : 'Explain in EN / AR'}</button>{(id === 'bank_account' || id.startsWith('residential_lease@')) && <button className="ls-btn secondary" disabled={!!busy} onClick={() => void run('draft')}>{busy === 'draft' ? 'Preparing letter…' : 'Draft paperwork'}</button>}</div><div aria-live="polite">{busy && <div className="loading-skeleton" aria-label="Preparing response" />}{error && <p role="alert" className="crit-text">{error}</p>}{explanation && <section className="ai-response"><h3>{t('Why this step matters')}</h3><p lang="en">{explanation.en}</p><p lang="ar" dir="rtl">{explanation.ar}</p><strong>{explanation.actionToday}</strong></section>}{draft && <section className="ai-response"><h3>{draft.subject}</h3><div className="bilingual-letter">{(['en', 'ar'] as const).map(lang => <div key={lang} lang={lang} dir={lang === 'ar' ? 'rtl' : 'ltr'}><button className="ls-text-button" onClick={() => void copy(draft[lang], lang)}>{copied === lang ? 'Copied' : `Copy ${lang.toUpperCase()}`}</button><p className="letter-text">{draft[lang]}</p></div>)}</div></section>}</div>{id === 'bank_account' && <BankableForm scheduled={scheduled} dispatch={dispatch} />}</div></dialog>;
}
