import { useState } from 'react';
import { motion, useReducedMotion } from 'motion/react';
import { addDays, formatDay, type Node, type ScheduledPlan } from '../model/plan';
type Row = { label: string; ids: string[]; header?: boolean; collapsed?: boolean };
export default function Timeline({ scheduled, onSelect }: { scheduled: ScheduledPlan; onSelect: (id: string) => void }) {
  const [hover, setHover] = useState<string | null>(null);
  const reduced = useReducedMotion();
  const nodes = Object.values(scheduled.nodes);
  const rows: Row[] = [{ label: 'Company', ids: [], header: true }, ...nodes.filter(n => !n.personId && !n.milestone).map(n => ({ label: n.label, ids: [n.id] })), { label: 'People', ids: [], header: true }];
  for (const person of scheduled.people.filter(p => p.family)) rows.push({ label: `${person.name} · ${person.role}`, ids: nodes.filter(n => n.personId === person.id && !n.milestone && !n.tags?.includes('family')).map(n => n.id) });
  const others = scheduled.people.filter(p => !p.family);
  if (others.length) rows.push({ label: `${others.length} more people, same path`, ids: nodes.filter(n => others.some(p => p.id === n.personId) && !n.milestone && !n.tags?.includes('family')).map(n => n.id), collapsed: true });
  rows.push({ label: 'Families', ids: [], header: true });
  for (const n of nodes.filter(n => n.tags?.includes('family') && !n.milestone)) rows.push({ label: n.label, ids: [n.id] });
  rows.push({ label: 'After go-live', ids: [], header: true }, { label: 'Obligations', ids: nodes.filter(n => n.tags?.includes('obligation')).map(n => n.id) });
  const weeks = Math.ceil(Math.max(...Object.values(scheduled.schedule).map(s => s.finish)) / 7) + 1;
  const labelWidth = 260, unit = 27, width = Math.max(1000, labelWidth + weeks * unit + 30), height = rows.length * 34 + 85;
  const x = (day: number) => labelWidth + day / 7 * unit;
  const bar = (node: Node, y: number) => {
    const s = scheduled.schedule[node.id], risk = (node.pReject ?? 0) * (node.retryDays ?? node.medianDays);
    const color = s.onCriticalPath ? 'var(--crit)' : 'var(--accent)';
    return <g key={node.id} role="button" tabIndex={0} aria-label={`${node.label}, ${s.expectedDays.toFixed(1)} days${s.onCriticalPath ? ', critical path' : ''}`} data-tour={node.id === 'bank_account' ? 'bank-bar' : undefined} onClick={() => onSelect(node.id)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onSelect(node.id); } }} onMouseEnter={() => setHover(node.id)} onMouseLeave={() => setHover(null)} onFocus={() => setHover(node.id)} onBlur={() => setHover(null)}><title>{`${node.label} · ${node.owner}\nMedian ${node.medianDays} d · p80 ${node.p80Days} d · expected ${s.expectedDays.toFixed(1)} d\n${formatDay(scheduled.company.startDate, s.start)} → ${formatDay(scheduled.company.startDate, s.finish)}\n${node.source}`}</title>{node.milestone ? <path d={`M ${x(s.start)} ${y - 6} l 6 6 -6 6 -6 -6 Z`} fill={color} /> : <><motion.g style={{ originX: 0, originY: 0 }} initial={false} animate={{ x: x(s.start), scaleX: Math.max(.12, s.expectedDays - risk) / 7 * unit }} transition={{ duration: reduced ? 0 : .25, ease: [.22, 1, .36, 1] }}><rect y={y - 9} width="1" height="18" rx=".05" fill={color} opacity={s.onCriticalPath ? 1 : .85} /></motion.g>{risk > 0 && <rect x={x(s.finish - risk)} y={y - 9} width={risk / 7 * unit} height="18" rx="2" fill={color} fillOpacity=".35" stroke={color} strokeDasharray="3 2" />}{node.id === 'bank_account' && <text x={x(s.finish) + 5} y={y + 4} fontSize="10" fill="var(--muted)">{Math.round((node.pReject ?? 0) * 100)}% retry risk</text>}</>}</g>;
  };
  const hovered = hover && scheduled.nodes[hover];
  return <section className="panel timeline-panel" data-tour="timeline"><div className="panel-title"><div><span className="eyebrow">ONE COMPANY. EVERY PERSON.</span><h2>Your landing sequence</h2></div><div className="timeline-legend"><span>━ Critical path</span><span>━ Parallel work</span></div></div><p className="muted">Select a step for its source, dependencies and next action. Scroll across the timeline for annual deadlines.</p><div className="timeline-scroll" tabIndex={0} aria-label="Scrollable company timeline"><svg width={width} height={height} role="group" aria-label="Schedule in weeks">{Array.from({ length: weeks + 1 }, (_, i) => { const date = addDays(scheduled.company.startDate, i * 7), prior = addDays(scheduled.company.startDate, (i - 1) * 7); return <g key={i}><line x1={x(i * 7)} x2={x(i * 7)} y1="52" y2={height} stroke="var(--line)" /><text x={x(i * 7)} y="46" fontSize="10" fill="var(--muted)">{i}</text>{(i === 0 || date.getUTCMonth() !== prior.getUTCMonth()) && <text x={x(i * 7)} y="20" fontSize="11" fill="var(--fg)">{date.toLocaleDateString('en-GB', { month: 'short', year: '2-digit', timeZone: 'UTC' })}</text>}</g>; })}<text x="16" y="46" fill="var(--muted)" fontSize="11">WEEK FROM START</text>{rows.map((row, i) => { const y = 78 + i * 34; return <g key={`${row.label}-${i}`}><text x="16" y={y + 4} fill={row.header ? 'var(--fg)' : 'var(--muted)'} fontSize={row.header ? '12' : '11'} fontWeight={row.header ? '600' : '400'}>{row.label}</text>{row.header ? <line x1={labelWidth} x2={width} y1={y} y2={y} stroke="var(--line)" /> : row.collapsed ? <g role="button" tabIndex={0} aria-label={row.label} onClick={() => onSelect(row.ids[0])} onKeyDown={e => { if (e.key === 'Enter') onSelect(row.ids[0]); }}><rect x={x(Math.min(...row.ids.map(id => scheduled.schedule[id].start)))} y={y - 9} width={(Math.max(...row.ids.map(id => scheduled.schedule[id].finish)) - Math.min(...row.ids.map(id => scheduled.schedule[id].start))) / 7 * unit} height="18" fill="var(--accent)" opacity=".45" rx="2" /></g> : row.ids.map(id => bar(scheduled.nodes[id], y))}</g>; })}<motion.g initial={false} animate={{ x: x(scheduled.goLiveDay) }} transition={{ duration: reduced ? 0 : .25, ease: [.22, 1, .36, 1] }}><line y1="52" y2={height} stroke="var(--crit)" strokeDasharray="5 4" /><text y="33" fontSize="10" fill="var(--crit)">Go-live {scheduled.goLiveDate}</text></motion.g></svg></div><div className="timeline-inspector" aria-live="polite">{hovered ? <><strong>{hovered.label}</strong> · {hovered.owner} · median {hovered.medianDays} d · p80 {hovered.p80Days} d · expected {scheduled.schedule[hovered.id].expectedDays.toFixed(1)} d<p>{formatDay(scheduled.company.startDate, scheduled.schedule[hovered.id].start)} → {formatDay(scheduled.company.startDate, scheduled.schedule[hovered.id].finish)}</p><small>{hovered.source}</small></> : <span>Solid bars show review time. Dashed extensions show expected retry time.</span>}</div></section>;
}


